### ISSUE TITLE
Missing arrest code causes crash

### ISSUE THREAD

**Issue by arlandism** [CityOfDetroit/crime-viewer#72]
Hey, love the tool. I was exploring some of the data and the app crashed on me. Here's the trace:
```
react-dom.production.min.js:4636 TypeError: Cannot read properties of undefined (reading 'description')
    at C (Intersection.js:29:50)
    at da (react-dom.production.min.js:3610:7)
    at Ps (react-dom.production.min.js:6612:11)
    at Ou (react-dom.production.min.js:5648:11)
    at Iu (react-dom.production.min.js:5637:9)
    at bu (react-dom.production.min.js:5393:11)
    at react-dom.production.min.js:2829:17
    at e.unstable_runWithPriority (scheduler.production.min.js:270:12)
    at Hi (react-dom.production.min.js:2794:10)
    at Ji (react-dom.production.min.js:2824:7)
```

Poking through the code and the data being debugged in the console, I noticed an arrest charge (`"13004"`) that's not found in the [list of arrestCodes](https://github.com/CityOfDetroit/crime-viewer/blob/master/src/data/arrestCodes.js). I'm guessing the static list of codes there is just stale. It'd probably be good to have a fallback mechanism (i.e. try catch, default data) so a missing arrest code doesn't cause a crash.

**Comment by benterova** [comment]
Addressed in #80
